# Generated by Django 2.0.7 on 2018-08-07 07:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular type', primary_key=True, serialize=False)),
                ('buildingtype', models.CharField(help_text='Enter type', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular project', primary_key=True, serialize=False)),
                ('title', models.CharField(default='NIL', help_text='Enter phase name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular project', primary_key=True, serialize=False)),
                ('city', models.CharField(help_text='Enter city', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular project', primary_key=True, serialize=False)),
                ('country', models.CharField(help_text='Enter country', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Documentinstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular project', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter document name', max_length=200)),
                ('doc', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('comment', models.TextField(help_text='Enter comments', null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular project', primary_key=True, serialize=False)),
                ('title', models.CharField(default='NIL', help_text='Enter phase name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular project', primary_key=True, serialize=False)),
                ('project_name', models.CharField(help_text='Enter project name', max_length=200)),
                ('project_description', models.TextField(help_text='Enter project description', null=True)),
                ('project_description1', models.TextField(help_text='Enter project description', null=True)),
                ('GFA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('kickoff_meeting', models.BooleanField(default=False)),
                ('kickoff_meeting_date', models.DateField(blank=True, help_text='Enter the following format: YYYY-MM-DD', null=True)),
                ('concept_DAP', models.BooleanField(default=False)),
                ('concept_DAP_date', models.DateField(blank=True, help_text='Enter the following format: YYYY-MM-DD', null=True)),
                ('mockup_DAP', models.BooleanField(default=False)),
                ('mockup_DAP_date', models.DateField(blank=True, help_text='Enter the following format: YYYY-MM-DD', null=True)),
                ('design_drawing_approved', models.BooleanField(default=False)),
                ('construction', models.BooleanField(default=False)),
                ('construction_date', models.DateField(blank=True, help_text='Enter the following format: YYYY-MM-DD', null=True)),
                ('pop_team', models.BooleanField(default=False)),
                ('pop_team_date', models.DateField(blank=True, help_text='Enter the following format: YYYY-MM-DD', null=True)),
                ('IST', models.BooleanField(default=False)),
                ('IST_date', models.DateField(blank=True, help_text='Enter the following format: YYYY-MM-DD', null=True)),
                ('completion', models.BooleanField(default=False)),
                ('completion_date', models.DateField(blank=True, help_text='Enter the following format: YYYY-MM-DD', null=True)),
                ('opening_date', models.DateField(blank=True, help_text='Enter the following format: YYYY-MM-DD', null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Country')),
            ],
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Phase'),
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Project'),
        ),
    ]
