# Generated by Django 2.0.7 on 2018-08-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_description1',
        ),
        migrations.AddField(
            model_name='project',
            name='buildingtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.BuildingType'),
        ),
    ]
