# Generated by Django 2.0.7 on 2018-08-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180807_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinstance',
            name='comment',
            field=models.TextField(blank=True, help_text='Enter comments', null=True),
        ),
    ]
