# Generated by Django 2.0.7 on 2018-08-08 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_documentinstance_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='personnel',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
