# Generated by Django 2.0.7 on 2018-08-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('portal', '0006_remove_project_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access_personnel',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
