# Generated by Django 2.0.7 on 2018-08-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20180808_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='dos',
            field=models.DateField(blank=True, null=True),
        ),
    ]
