# Generated by Django 2.0.7 on 2018-08-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_documentinstance_dos'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='reviewed_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], default='Pending', max_length=8),
        ),
    ]
