# Generated by Django 2.0.7 on 2018-08-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_documentinstance_reviewed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='resubmission_required',
            field=models.BooleanField(default=False),
        ),
    ]
