# Generated by Django 2.0.7 on 2018-08-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_documentinstance_resubmission_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinstance',
            name='resubmission_required',
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='reviewed_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Resubmission Required', ' Resubmission Required')], default='Pending', max_length=8),
        ),
    ]
