# Generated by Django 2.0.7 on 2018-08-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20180810_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinstance',
            name='reviewed_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Resubmission Required', ' Resubmission Required')], default='Pending', max_length=22),
        ),
    ]
