# Generated by Django 2.0.7 on 2018-08-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_documentinstance_dor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='refdoc',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ref'),
        ),
    ]
