# Generated by Django 2.0.7 on 2018-08-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_documentinstance_refdoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentinstance',
            name='reviewed_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Reviewed', 'Reviewed'), ('Resubmission Required', ' Resubmission Required')], default='Pending', max_length=22),
        ),
    ]
