# Generated by Django 2.0.7 on 2018-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_auto_20180810_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='feedback_document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/com'),
        ),
    ]
