# Generated by Django 2.0.7 on 2018-08-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_auto_20180810_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateinstance',
            name='name1',
            field=models.CharField(default='test', help_text='Enter template instance name', max_length=200),
        ),
        migrations.AddField(
            model_name='templateinstance',
            name='name2',
            field=models.CharField(default='test', help_text='Enter template instance name', max_length=200),
        ),
        migrations.AlterField(
            model_name='templateinstance',
            name='name',
            field=models.CharField(default='test', help_text='Enter template instance name', max_length=200),
        ),
    ]
