# Generated by Django 2.0.7 on 2018-08-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_auto_20180813_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateinstance',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='templateinstance',
            name='name2',
        ),
    ]
