# Generated by Django 2.0.7 on 2018-08-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_auto_20180813_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateinstance',
            name='templateset',
        ),
        migrations.DeleteModel(
            name='templateinstance',
        ),
        migrations.DeleteModel(
            name='templateset',
        ),
    ]
