# Generated by Django 2.0.7 on 2018-08-13 06:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20180813_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='templateinstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular project', primary_key=True, serialize=False)),
                ('title', models.CharField(default='NIL', help_text='Enter phase name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='templateset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular project', primary_key=True, serialize=False)),
                ('name', models.CharField(default='NIL', help_text='Enter phase name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='templateinstance',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.templateset'),
        ),
    ]
