# Generated by Django 2.0.7 on 2018-08-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_auto_20180813_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateinstance',
            name='project',
        ),
        migrations.AddField(
            model_name='templateinstance',
            name='templateset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.templateset'),
        ),
    ]
