# Generated by Django 2.0.7 on 2018-08-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0032_auto_20180813_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateinstance',
            name='refdoc',
            field=models.FileField(blank=True, null=True, upload_to='uploads/templateref'),
        ),
    ]
